### ISSUE TITLE
iOS Build Missing util_platforms.h

### ISSUE THREAD

**Issue by playfulsystems** [ccrma/chunity#11]
When building for iOS, I get the following error:
Libraries/Chunity/Plugins/iOS/ulib_std.cpp:36:10 'util_platforms.h' file not found

<img width="500" alt="Screenshot 2024-04-08 at 1 46 34 PM" src="https://github.com/ccrma/chunity/assets/44376983/14fee7c1-f094-4b8f-b929-1c1194bfcb64">

**Comment by gewang** [comment]
this has been fixed as of 2227eb4; will be in the next release (v2.2.0)
cc @eitomurakami
